### ISSUE TITLE
Issues in trainSet and testSet

### ISSUE THREAD

**Issue by nopa607** [gopuvenkat/MHCAttnNet#10]
hello!
I get your datasets from FIGSHARE, and i found some repeated items in classI/train.csv and classI/test.csv. 
The same situation appear in 5_cross_val.
I guess some prepocessing may be implemented before training the model.
Could u help me sovle this problem?

**Comment by AayushGrover** [comment]
Hello!

As mentioned in https://github.com/openvax/mhcflurry/issues/129, the uncertainty in the measurement values can be high. Hence, we train the model on all the data points.

**Comment by nopa607** [comment]
i get that . thanks for your answer!
