### ISSUE TITLE
Questions about allele sequences

### ISSUE THREAD

**Issue by KiAkize** [gopuvenkat/MHCAttnNet#11]
I have several questions about class II data used in codes.
(1) I analyzed the DR molecule and the source sequence and found that it was intercepted from the source sequence. Why are the sequence lengths selected by different DR molecules different? According to what criteria to choose the length?
(2) How to determine the input sequence for a new DR molecule, which is not in the alleles_II.py dictionary?
(3) How to deal with DP and DQ molecules, such as HLA-DPA10103-DPB10101?

**Comment by AayushGrover** [comment]
(1) The amino acid sequences were picked from the [NCBI's protein database](https://www.ncbi.nlm.nih.gov/protein/).
(2)  You can find the new input sequences from the abovementioned source. You can simply add those mappings to the alleles_II.py file.
(3) MHCAttnNet can deal with DP, DQ molecules as long as their amino acid sequences are added to the alleles_II.py.

**Comment by KiAkize** [comment]
(1) In response to question 1, I want to ask why the length of the amino acid sequence used is so different? The length is divided into 86, 88, 89, 174, 183, 220, 232. Why not use fixed-length sequences?
(4) In addition, I want to ask the fourth question. I used the HLA-DR part of 5_cross data set of the [website](http://www.cbs.dtu.dk/suppl/immunology/NetMHCIIpan-3.2/) and modified the format to the format required by your code. When I use this dataset for training, pytorch will report an error: WARNING:root:NaN or Inf found in input tensor. Why is this?

**Comment by AayushGrover** [comment]
(1) NCBI's protein database consists of various length sequences and this is further explained in the Introduction section of our paper. 
(4) Could you please share the complete log of the error to help us pin-point why this might be happening?

**Comment by KiAkize** [comment]
> (1) NCBI's protein database consists of various length sequences and this is further explained in the Introduction section of our paper.
> (4) Could you please share the complete log of the error to help us pin-point why this might be happening?

(4) I uploaded the 5 cross data sets I have compiled and the updated allele_II.py, the google drive [link](https://drive.google.com/drive/folders/1np9IFfSKHr0bBI5NEZpK9zjS8Tw1dABx?usp=sharing) is here. If it is convenient, please download and test it.

**Comment by KiAkize** [comment]
> (1) NCBI's protein database consists of various length sequences and this is further explained in the Introduction section of our paper.
> (4) Could you please share the complete log of the error to help us pin-point why this might be happening?

(1) Regarding question 1, I still don't know how the amino acids of allele are selected. For example, search for `HLA-DRB1*03:01 `on [NCBI](https://www.ncbi.nlm.nih.gov/protein/?term=HLA-DRB1*03%3A01), there are so many links give partial sequence for `HLA-DRB1*03:01` such as: [1](https://www.ncbi.nlm.nih.gov/protein/SIT52285.1), [2](https://www.ncbi.nlm.nih.gov/protein/SIT52295.1), [3](https://www.ncbi.nlm.nih.gov/protein/AIB55784.1), [4](https://www.ncbi.nlm.nih.gov/protein/AQU14344.1?report=fasta). According to what rules, choose [4](https://www.ncbi.nlm.nih.gov/protein/AQU14344.1?report=fasta) to write into allele_II.py?

**Comment by AayushGrover** [comment]
> > (1) NCBI's protein database consists of various length sequences and this is further explained in the Introduction section of our paper.
> > (4) Could you please share the complete log of the error to help us pin-point why this might be happening?
> 
> (4) I uploaded the 5 cross data sets I have compiled and the updated allele_II.py, the google drive [link](https://drive.google.com/drive/folders/1np9IFfSKHr0bBI5NEZpK9zjS8Tw1dABx?usp=sharing) is here. If it is convenient, please download and test it.

Unfortunately, we do not have the access to the machines anymore. We can help you out if you can provide the complete error message.
