### ISSUE TITLE
Specify open-source license?

### ISSUE THREAD

**Issue by chuck-benz** [gopuvenkat/MHCAttnNet#12]
Thanks for the great contribution and excellent work with MHCAttnNet.  I'm curious if you could specify the license the code is released under (and perhaps add a license.txt to the repository if it's not too much trouble)?  Thanks!

**Comment by gopuvenkat** [comment]
Hi! Commit ce604dca638258b0f553601b5bb78b310fdc752b licenses the code under GPL v3. Thanks!
