### ISSUE TITLE
Input.csv file in Pre-process

### ISSUE THREAD

**Issue by KiAkize** [gopuvenkat/MHCAttnNet#9]
I have downloaded Dataset at figshare.
However, I could not find any Input.csv having same columns as IEDB for pre-processing.
The dataset at figshare  has provided  train.csv, val.csv and test.csv files which are not used for pre-processing.
**Where can I get the input.csv file to pre-process?**

**Comment by AayushGrover** [comment]
The original input data can be downloaded from https://www.iedb.org/database_export_v3.php. 
Please download the **mhc_ligand_full (single_file.zip)**.

**Comment by KiAkize** [comment]
> The original input data can be downloaded from https://www.iedb.org/database_export_v3.php.
> Please download the **mhc_ligand_full (single_file.zip)**.

:) Thank you! I will try.

**Comment by KiAkize** [comment]
> > The original input data can be downloaded from https://www.iedb.org/database_export_v3.php.
> > Please download the **mhc_ligand_full (single_file.zip)**.
> 
> :) Thank you! I will try.

I download the mhc_ligand_full.csv(single_file.zip) then pre-process it. (add '--save True' in command)
The output.csv file contain 62506 lines which are **all class II MHC** related datas.
In the paper it is said that 'Our final dataset comprises of 491 018 class I MHC-allele data- points covering 161 different HLAs and 64 954 class II MHC-allele data-points covering 49 different HLAs.'
Is that pre-processed output.csv file all data? 
If not, where can I get rest data?

**Comment by AayushGrover** [comment]
Please look at lines **30-35 and 48-54** of [preprocess.py](https://github.com/gopuvenkat/MHCAttnNet/blob/master/src/preprocess.py). You need to comment/uncomment these lines and run again to get the output data of an appropriate class. The code file has the comments to help you out with this. Please have a look at it.

**Comment by KiAkize** [comment]
> Please look at lines **30-35 and 48-54** of [preprocess.py](https://github.com/gopuvenkat/MHCAttnNet/blob/master/src/preprocess.py). You need to comment/uncomment these lines and run again to get the output data of an appropriate class. The code file has the comments to help you out with this. Please have a look at it.

Thank you! These lines are awesome.
On the other hand, the dataset from figshare contains class I and class II MHC train, val, test files.
Can these files be loaded to run src/train.py directly?

**Comment by AayushGrover** [comment]
Yes, these files will be directly loaded when you run src/train.py. However, if you get any path-related errors, please mention appropriate paths and filenames in src/config.py.
